name: Build & Deploy

on: [push, pull_request]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      
      - uses: actions/checkout@v4
        with:
          repository: openfl/OpenFLDevelopersGuide
          path: OpenFLDevelopersGuide
      
      - uses: actions/checkout@v4
        with:
          repository: openfl/AS3ConversionGuide
          path: AS3ConversionGuide

      - name: Build
        run: |
          npx honkit@6 build OpenFLDevelopersGuide
          npx honkit@6 build AS3ConversionGuide
      
      - name: Prepare deploy
        run: |
          mkdir deploy
          mkdir deploy/openfl-developers-guide
          mkdir deploy/as3-conversion-guide
          cp -r OpenFLDevelopersGuide/_book/* deploy/openfl-developers-guide
          cp -r AS3ConversionGuide/_book/* deploy/as3-conversion-guide
          cp index.html deploy/index.html
          cp CNAME deploy/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.repository == 'openfl/books.openfl.org' && github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com